### ISSUE TITLE
Update data product description and ancillary files

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_app#205]
Give the product owners the possibility of editing the product description and uploading new ancillary files (and deleting old ones) to an existing data product in order to update its documentation. This is especially useful for LSST official data products, for which we will produce notebooks with instructions for access via API, so the process ID present in the notebook should be already defined. It means that the data product should be uploaded in advance of preparing the notebook.  

```[tasklist]
### Tasks
- [x] Manage product update date
- [x] Manage update and creation date for each uploaded file
- [x] Admin user can update all products.
- [x] Update Product Metadata
- [x] Update Product FIles
```
