### ISSUE TITLE
[BUG] PZ server instability 

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_app#208]
Sometimes the PZ server shows no data products, but this is not a constant behavior. I suspect it reached the timeout limit.  

![image](https://github.com/linea-it/pzserver_app/assets/9534570/8200fde7-e5f2-4f11-a7f9-25f7da361e13)

The correct page should show this: 
![image](https://github.com/linea-it/pzserver_app/assets/9534570/9f64184f-06a2-4e71-b6d5-eeeb40bba799)
 

Also, sometimes the data product download page appears incomplete, without the file names below the download button and the description file preview. 

![image](https://github.com/linea-it/pzserver_app/assets/9534570/22f5154b-aa6b-4302-b80d-bde5bb6203cf)

The correct page should show this: 
![image](https://github.com/linea-it/pzserver_app/assets/9534570/7d27a467-8241-46e9-89a6-19e8202c553d)

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/pzserver_app/issues/210
- [x] Show "loading..." message in all fields where it takes some time to open the contents
- [ ] Show error message
```

**Comment by gschwend** [comment]
A new bug was found: a timeout error occurs when downloading a file
