### ISSUE TITLE
column product status 

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_app#212]
Please add a column to show the product status on both data products pages (rubin official and users). The status must refer to the pipeline status, so the user can monitor the creation of a new product via the pz server pipelines. To avoid confusion with the registration status of products added via the upload tool, please follow the suggestions below (or equivalent):  
  
```[tasklist]
### Tasks
- [ ] Rename current status as registration_status
- [ ] Create a new field called pipeline_status
- [ ] Create a new field: upload_by_user (bool)
- [ ] The product list will show registration status or pipeline status, depending on the product origin (oploaded by user or not). The display name of the status column on the products page is simple "Status".
```
