### ISSUE TITLE
Fix layout standards

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_app#231]
```[tasklist]
### Tasks
- [x] Add breadcrumbs (full navigation path with return button) to the pipelines pages (both)
- [x] Change title position (left align to standardize all pages)
- [x] fix bug when zoom in
```
