### ISSUE TITLE
Run the x-matching in command line mode

### ISSUE THREAD

**Issue by gschwend** [linea-it/pzserver_app#273]
```[tasklist]
### Tasks
- [x] provide a spec-z catalog file (parquet)
- [x] run using lsdb
- [x] QA notebook  for validation
```

**Comment by luigilcsilva** [comment]
This may be closed by the "Adding the notebooks with the DES DR2 and 2dFLenS x-matching examples, using hipscat_import and lsdb #25" pull request in the jupyterhub-tutorial repository ([link to the pull request](https://github.com/linea-it/jupyterhub-tutorial/pull/25)).
