### ISSUE TITLE
Deploy app on homolog environment (-dev)

### ISSUE THREAD

**Issue by deborajanini** [linea-it/pzserver_app#285]
```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/pzserver_app/issues/288
- [ ] https://github.com/linea-it/pzserver_app/issues/289
- [ ] https://github.com/linea-it/pzserver_app/issues/290
```

**Comment by deborajanini** [comment]
@gschwend necessito do size aqui também
